### ISSUE TITLE
Create README for how we create new build tasks

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/pages-cf-build-tasks#2]
This repo is currently mostly a stub to get https://github.com/cloud-gov/pages-core/pull/4248 working correctly.

I'd like to rewrite it to act as a monorepo for all build task running as `cf tasks`. First, we should have an ADR and/or README covering the following topics:
- [x] Construct a documented pattern for how new tasks are created
- [x] Create a shared library for common functions between tasks (status update, artifact saving, error handling, etc).
- [ ] How to build from source + harden containers
- [ ] How to setup CI Pipelines for multiple environments + multiple apps

## Acceptance Criteria

- [ ] Write a document outlining the desired architecture

**Comment by apburnes** [comment]
To do schedule time to walk through PR

**Comment by drewbo** [comment]
Closed via https://github.com/cloud-gov/pages-cf-build-tasks/pull/3
